In [29]:
import numpy as np


In [30]:
my_list = [1, 2, 3, 4]
array = np.array([1, 2, 3, 4])
array = array * 2 
print(array)
print(type(array))

[2 4 6 8]
<class 'numpy.ndarray'>


 Multidimensional Arrays 

In [31]:
# Multidimensional Arrays 
array = np.array([[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']], 
                  [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']], 
                  [['S', 'T', 'U'], ['V', 'W', 'X'], ['Y', 'Z', ' ']]])
word = array[0, 0, 0] + array[2, 0, 0] + array[2, 1, 0]
print(word)

ASV


In [32]:
array = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12], 
                  [13, 14, 15, 16]])
# array[start:end:step]
print(array[0:4:2])

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [33]:
array = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12], 
                  [13, 14, 15, 16]])
# array[start:end:step]
print(array[:, 2])

[ 3  7 11 15]


In [34]:
array = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12], 
                  [13, 14, 15, 16]])
# array[start:end:step]
print(array[:, 0:3])

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [35]:
array = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12], 
                  [13, 14, 15, 16]])
# array[start:end:step]
print(array[0:2, 2:])

[[3 4]
 [7 8]]


 Scalar Arithmetic 
 Vectorized Math Funcs 
 Exrecise 
 Elemet-Wise Arithemtic 
 Comparison Operataros

In [36]:
# Scalar Arithmetic 
array = np.array([1, 2, 3])
print(array + 1)
print(array - 2)
print(array * 3)
print(array / 4)


[2 3 4]
[-1  0  1]
[3 6 9]
[0.25 0.5  0.75]


In [37]:
array = np.array([1.01, 2.5, 3.99])


print(np.sqrt(array))

print(np.round(array))

[1.00498756 1.58113883 1.99749844]
[1. 2. 4.]


In [ ]:
# Vectorized Math Funcs 
# Exrecise 

radii = np.array([1, 2, 3])

print(np.pi * radii ** 2)

[ 3.14159265 12.56637061 28.27433388]


In [39]:
# Elemet-Wise Arithemtic 
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
print(array1 + array2 )
print(array1 - array2 )
print(array1 * array2 )
print(array1 / array2 )
print(array1 ** array2 )

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [40]:
# Comparison Operataros
scores = np.array([91, 55, 100, 73, 82, 64])
print(scores == 100 )
print(scores >= 60  )
print(scores <= 60  )

[False False  True False False False]
[ True False  True  True  True  True]
[False  True False False False False]


In [41]:
scores = np.array([91, 55, 100, 73, 82, 64])
scores[scores < 60] = 0
print(scores)

[ 91   0 100  73  82  64]


# Broadcasting Allows NumPy To Perform Operations On Array 
# With Different Shape By Virtually Expanding Dimensions 
# SO They Match The Larger Array's Shape. 

# The Dimensions Have The Same Size 
# OR 
# One Of The Dimensions Has a Size Of 1.

In [42]:
array3 = np.array([[1, 2, 3, 4], 
                   [5, 6, 7, 8], 
                   [9, 10, 11, 12], 
                   [13, 14, 15, 16]])
array4 = np.array([[1], [2], [3], [4]]) 

print(array3.shape)
print(array4.shape)

print(array3 * array4)


(4, 4)
(4, 1)
[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]
 [52 56 60 64]]


In [43]:
array5 = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
array6 = np.array([[[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]]])

print(array5 * array6)

[[[  1   2   3   4   5   6   7   8   9  10]
  [  2   4   6   8  10  12  14  16  18  20]
  [  3   6   9  12  15  18  21  24  27  30]
  [  4   8  12  16  20  24  28  32  36  40]
  [  5  10  15  20  25  30  35  40  45  50]
  [  6  12  18  24  30  36  42  48  54  60]
  [  7  14  21  28  35  42  49  56  63  70]
  [  8  16  24  32  40  48  56  64  72  80]
  [  9  18  27  36  45  54  63  72  81  90]
  [ 10  20  30  40  50  60  70  80  90 100]]]


# Aggregate Functions = Summarize Data And Typically
#                       Return a Single Value 


In [44]:
array7 = np.array([[1, 2, 3, 4, 5], 
                   [6, 7, 8, 9, 10]])
print(np.sum(array7))
print(np.mean(array7))
print(np.std(array7))
print(np.var(array7))
print(np.min(array7))
print(np.max(array7))
print(np.argmin(array7))
print(np.argmax(array7))

55
5.5
2.8722813232690143
8.25
1
10
0
9


In [45]:
array8 = np.array([[1, 2, 3, 4, 5], 
                   [6, 7, 8, 9, 10]])
print(np.sum(array, axis=0))

7.5


# Filtering = Refers To The Process Of Selecting Elements
#             From An Array That Match a Given Condition 

In [46]:
ages = np.array([[21, 17, 19, 20, 16, 30, 18, 65], 
                 [39, 22, 15, 99, 18, 19, 20, 21]])
teenagers = ages[ages < 18 ]
adults = ages[(ages >= 18)  & (ages < 65)]

seniors = ages[ages >= 65 ]

evens = ages[ages % 2 == 0]

odds = ages[ages % 2 != 0]

print(teenagers)
print(adults)
print(seniors)
print(evens)
print(odds)

[17 16 15]
[21 19 20 30 18 39 22 18 19 20 21]
[65 99]
[20 16 30 18 22 18 20]
[21 17 19 65 39 15 99 19 21]


In [47]:
ages = np.array([[21, 17, 19, 20, 16, 30, 18, 65], 
                 [39, 22, 15, 99, 18, 19, 20, 21]])

adults1 = np.where(ages >= 18, ages, 0)

print(adults1)

[[21  0 19 20  0 30 18 65]
 [39 22  0 99 18 19 20 21]]


In [48]:
rng = np.random.default_rng(seed=1)


print(rng.integers(low=1, high=101, size=(3, 2)))


[[48 52]
 [76 96]
 [ 4 15]]


In [49]:
np.random.seed(seed=1)
print(np.random.uniform(low=-1, high=1, size=(3, 2)))

[[-0.16595599  0.44064899]
 [-0.99977125 -0.39533485]
 [-0.70648822 -0.81532281]]


In [50]:
rng = np.random.default_rng()


array10 = np.array([1, 2, 3, 4, 5])
rng.shuffle(array)

print(array)

[2.5  3.99 1.01]


In [51]:
rng = np.random.default_rng()
fruits = np.array(["apple", "orange", "banana", "coconut", "pineapple"])
fruits = rng.choice(fruits, size=(3))
print(fruits)

['pineapple' 'pineapple' 'orange']
