In [21]:
import numpy as np
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([0, 1, 1, 1])
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [22]:
y

array([0, 1, 1, 1])

In [23]:
W = np.array([1, 1])
W

array([1, 1])

In [24]:
b = -0.5

In [25]:
def activation(z):
    if z> 0:
        return 1
    else:
        return 0

In [26]:
pred = []
for a in X:
    y_hat = np.dot(a,W)+b
    pred.append(activation(y_hat))
    

In [27]:
pred

[0, 1, 1, 1]

# Perceptron Learning 

In [28]:
import math 

In [29]:
epochs = 100
alpha = 0.2

In [30]:
W0 = np.random.random()
W1 = np.random.random()
W2 = np.random.random()
print("initial weights:")
print("W0=",W0, "W1=",W1, "W2=",W2)

initial weights:
W0= 0.7972760131727538 W1= 0.9873241399611379 W2= 0.28098646500739577


In [31]:
del_W0 = 1
del_W2 = 1
del_W1 = 1

In [32]:
train_data_temp = [[0,0,0], [0,0,1], [0,1,0], [0,1,1], [1,0,0], [1,0,1], [1,1,0], [1,1,1]]
train_data = np.asarray(train_data_temp)
op = np.array([0,1,1,1,1,1,1,1])

In [33]:
train_data

array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 1, 0],
       [1, 1, 1]])

In [34]:
op

array([0, 1, 1, 1, 1, 1, 1, 1])

In [35]:
y = (X*W)+b

In [36]:
bias = 0 
for i in range(epochs):
    for X in train_data:
        y_hat = W0*X[0] + W1*X[1] + W2*X[2] + bias 
        
        if (y_hat >= 0):
            act = 1
        else:
            act = 0
            err = op[j] - act 
            del_W0 = alpha*X[0]*err
            del_W1 = alpha*X[1]*err
            del_W2 = alpha*X[2]*err
            
            W0 = W0+ del_W0
            W1 = del_W1
            W2 = del_W2
            
            j = j+1
            print("epoch" , i+1, "error =", err)
            print(del_W0,del_W1,del_W2)
            
print("\nFinal Weights = ")
print("W0 = ",W0, "W1 = ",W1, "W2 = ",W2)            


Final Weights = 
W0 =  0.7972760131727538 W1 =  0.9873241399611379 W2 =  0.28098646500739577


# Classification Technical Terms
Scikit-Learn Classification Algorithms